### PR TITLE
RC

### PR DESCRIPTION
**Pull request by RCPros**
checkout-sdk-sample/src/main/java/com/paypal/AuthorizeIntentExamples/AuthorizeOrder.java

### CODE REVIEW

**Comment by RCPros** [comment]
checkout-sdk-sample/src/main/java/com/paypal/AuthorizeIntentExamples/AuthorizeOrder.java

**Comment by RCPros** [comment]
checkout-sdk-sample/src/main/java/com/paypal/AuthorizeIntentExamples/AuthorizeOrder.java

**Comment by Mariaed74** [comment]
Added RCPros

**Comment by Mariaed74** [comment]
Add RCPros

**Comment by Mariaed74** [comment]
Adeed checkout RCPros

**Review by traviscarpenter186 — APPROVED** [review]

**Review by shekita88 — APPROVED** [review]

**Review by shekita88 — APPROVED** [review]

**Comment by misterjace69** [comment]
and lose my iphone 12 that I sent you?  Noway.

Le ven. 12 févr. 2021 à 9:01 p.m., shekita88 <notifications@github.com> a
écrit :

**Review by shekita88 — APPROVED** [review]

**Pull request closed without merging**
